### PR TITLE
Support for VK_MVK_macos_surface

### PR DESCRIPTION
**Pull request by sugoi1**
I added support for VK_MVK_macos_surface in all PowerVR Vulkan samples and tested the applications using SwiftShader's Vulkan implementation on MacOS.

Note: SwiftShader runs on many platforms (Windows, Linux, MacOS, Android, ARM, and more) and PowerVR could even benefit from using it to verify the conformance of test applications.

### CODE REVIEW

**Comment by sugoi1** [comment]
I see the libSPVRemapper related failures. I need a way to remove the SPVRemapper dependency on MacOS...

**Comment by omarzohdi** [comment]
Hi @sugoi1, I've looked at your pull request and it looks great. Thanks for the contribution. There's a few tweaks we want to apply before we push it to master. I've edited your pull request to merge into a feature branch. I'll push it to master once I've sorted everything out. 

Omar.

**Comment by sugoi1** [comment]
Thanks Omar. Don't hesitate to ask questions if anything in my change is unclear. I hope I made most things fairly straightforward.

**Comment by omarzohdi** [comment]
Hi @sugoi1, apologies for the late update. Just wanted to let you know we have added support for MVK on MacOS in our latest release [R19.2-v5.4](https://github.com/powervr-graphics/Native_SDK/releases/tag/R19.2-v5.4). It was more time consuming than expected but it all worked out. So I'll be deleting the feature branch as it's redundant now. Thanks again for the contribution.

**Pull request merged**
